refactor: pipelines and taskfiles

diff --git a/.github/workflows/pull-request.main.yml b/.github/workflows/pull-request.main.yml
--- a/.github/workflows/pull-request.main.yml
+++ b/.github/workflows/pull-request.main.yml
@@ -15,7 +15,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: 📥 Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: 🛠️ Setup Required Dependencies
         uses: ./.github/actions/setup
@@ -24,11 +24,14 @@ jobs:
         env:
           NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
 
+      - name: 🏗️ Build
+        run: task build
+
       - name: Format
         run: |
-          task fmt:refactor -- .
-          task fmt:csharp -- .
-          task fmt:prettier -- .
+          task fmt:refactor
+          task fmt:csharp 
+          task fmt:prettier
 
       - name: Commit changes
         uses: stefanzweifel/git-auto-commit-action@v4
@@ -37,12 +40,13 @@ jobs:
           branch: ${{ github.head_ref }}
 
   test:
-    name: 🏗️ Build
-    needs: format
+    name: 🧪 Test
+    needs:
+      - format
     runs-on: ubuntu-latest
     steps:
       - name: 📥 Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: 🛠️ Setup Required Dependencies
         uses: ./.github/actions/setup
@@ -51,17 +55,32 @@ jobs:
         env:
           NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
 
-      - name: 💅 Format
-        run: |
-          task fmt:refactor -- .
-          task fmt:csharp -- .
-          task fmt:prettier -- .
-
       - name: 🏗️ Build
-        run: task src:build
+        run: task ci:build
 
       - name: 🧪 Test
-        run: task src:test
+        run: task ci:test
 
-      - name: 🧳 Pack (dry-run)
-        run: task src:pack
+      - name: Test Report
+        uses: dorny/test-reporter@v2
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: .NET Tests # Name of the check run which will be created
+          path: test-results.trx # Path to test results
+          reporter: dotnet-trx # Format of test results
+
+      - name: 🧳 Pack
+        run: task ci:pack
+
+  security:
+    name: 🔒 Security
+    needs:
+      - format
+    runs-on: ubuntu-latest
+    steps:
+      - name: 📥 Checkout
+        uses: actions/checkout@v4
+      - name: 🔒 Security Checks
+        uses: ./.github/actions/security
+        with:
+          snyk_token: ${{ secrets.SNYK_TOKEN }}
diff --git a/.github/workflows/push.main.yml b/.github/workflows/push.main.yml
--- a/.github/workflows/push.main.yml
+++ b/.github/workflows/push.main.yml
@@ -10,14 +10,11 @@ permissions:
   pages: write
   id-token: write
 
-# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
-concurrency:
-  group: "pages"
-  cancel-in-progress: false
+env:
+  HUSKY: 0
 
 jobs:
-  release:
+  checks:
     name: Release
     runs-on: ubuntu-latest
     permissions:
@@ -36,29 +33,79 @@ jobs:
           NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
 
       - name: Build
-        run: task src:build
+        run: task ci:build
 
       - name: Test
-        run: task src:test
+        run: task ci:test
+
+      - name: Test Report
+        uses: dorny/test-reporter@v2
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: .NET Tests # Name of the check run which will be created
+          path: test-results.trx # Path to test results
+          reporter: dotnet-trx # Format of test results
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1
+        with:
+          token: ${{ secrets.CODE_COV_TOKEN }}
+
+  security:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/dotnet@master
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+  release:
+    name: Release
+    runs-on: ubuntu-latest
+    needs:
+      - checks
+      - security
+    permissions:
+      contents: write
+      pull-requests: write
+      packages: write
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up dependencies
+        uses: ./.github/actions/setup
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+        env:
+          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
 
       - name: Release Please
         id: release
         uses: google-github-actions/release-please-action@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          config-file: .config/release-please-config.json
+          # optional. customize path to .release-please-manifest.json
+          manifest-file: .config/.release-please-manifest.json
 
       - name: Create package
         if: ${{ steps.release.outputs.release_created }}
         run: |
-          task src:build-release
-          task src:pack
+          task ci:build
+          task ci:pack
 
       - name: Push packages to GPR
         if: ${{ steps.release.outputs.release_created }}
-        run: task src:publish
+        run: task ci:publish
 
   # publish-docs:
   #   concurrency:
   #     group: "pages"
   #     cancel-in-progress: false
+  #   needs:
+  #     - release
   #   environment:
   #     name: github-pages
   #     url: ${{ steps.deployment.outputs.page_url }}
